/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static void main(String[] args) {
        System.out.println("Hello Gradle!");
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
